### ISSUE TITLE
안녕하세요 ^^ 

### ISSUE THREAD

**Issue by JeongJaeSoon** [Siyeon-dev/Exercise-ProblemSolving#1]
안녕하세요 ^^

지나가다 관심이 생겨 들린 학생입니다.
_코딩 테스트 준비용 Repo_ 인지 궁금해서요~~

아! 혹시나 오해하실까바 덧붙이자면 **Issues 기능**을 써보고 싶어서 적는건 아니랍니다 ㅎㅎ

**Comment by Siyeon-dev** [comment]
안녕하세요 ~

알고리즘 능력 키울 겸해서 백준 문제 좀 풀어보려고 합니다 ~.~
Issues로 메일 보내는 게 이런 거군요 wow..~
답장 보내면 학생에게도 알림이 갈까요??
2021年6月2日 AM11:08 +0900、JeongJaeSoon ***@***.***> のメール:

**Comment by JeongJaeSoon** [comment]
아 네네! 메일로도 답장이 오네요~
알고리즘 능력 많이많이 키워주세요~
